// <auto-generated />
using System;
using HOT3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT3.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20251013044737_AddedPurchases")]
    partial class AddedPurchases
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT3.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Gooseberry",
                            ProductImageUrl = "DS-DM-Gooseberry.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 14.99m,
                            ProductStock = 32
                        },
                        new
                        {
                            ProductId = 2,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Blossom",
                            ProductImageUrl = "DS-DM-Blossom.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 14.99m,
                            ProductStock = 48
                        },
                        new
                        {
                            ProductId = 3,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Pomegranate & Gold",
                            ProductImageUrl = "DS-DM-PomegranateGold.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 16.99m,
                            ProductStock = 25
                        },
                        new
                        {
                            ProductId = 4,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Cobalt & Silver",
                            ProductImageUrl = "DS-DM-CobaltSilver.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 16.99m,
                            ProductStock = 40
                        },
                        new
                        {
                            ProductId = 5,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Clear",
                            ProductImageUrl = "DS-PF-Clear.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 7.99m,
                            ProductStock = 20
                        },
                        new
                        {
                            ProductId = 6,
                            ProductBrand = "Ultra Pro",
                            ProductColor = "Black",
                            ProductImageUrl = "UP-EG-JetBlack.jpg",
                            ProductName = "Eclipse Gloss",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 7,
                            ProductBrand = "Ultra Pro",
                            ProductColor = "Sky Blue",
                            ProductImageUrl = "UP-EG-SkyBlue.jpg",
                            ProductName = "Eclipse Gloss",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 8,
                            ProductBrand = "Ultra Pro",
                            ProductColor = "Apple Red",
                            ProductImageUrl = "UP-EM-AppleRed.jpg",
                            ProductName = "Eclipse Matte",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 9,
                            ProductBrand = "Ultra Pro",
                            ProductColor = "Forest Green",
                            ProductImageUrl = "UP-EM-ForestGreen.jpg",
                            ProductName = "Eclipse Matte",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 10,
                            ProductBrand = "Ultimate Guard",
                            ProductColor = "Orange",
                            ProductImageUrl = "UG-MC-Orange.jpg",
                            ProductName = "Matte Cortex",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 11,
                            ProductBrand = "Ultimate Guard",
                            ProductColor = "Purple",
                            ProductImageUrl = "UG-MC-Purple.jpg",
                            ProductName = "Matte Cortex",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 12,
                            ProductBrand = "Ultimate Guard",
                            ProductColor = "Petrol",
                            ProductImageUrl = "UG-MC-Petrol.jpg",
                            ProductName = "Matte Cortex",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 13,
                            ProductBrand = "Ultimate Guard",
                            ProductColor = "Pink",
                            ProductImageUrl = "UG-MC-Pink.jpg",
                            ProductName = "Matte Cortex",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        },
                        new
                        {
                            ProductId = 14,
                            ProductBrand = "Ultimate Guard",
                            ProductColor = "Yellow",
                            ProductImageUrl = "UG-MC-Yellow.jpg",
                            ProductName = "Matte Cortex",
                            ProductPrice = 9.99m,
                            ProductStock = 50
                        });
                });

            modelBuilder.Entity("HOT3.Models.Purchase", b =>
                {
                    b.Property<int>("PurchaseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PurchaseId"));

                    b.Property<int>("ProductId")
                        .HasColumnType("int");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("PurchaseId");

                    b.HasIndex("ProductId");

                    b.ToTable("Purchases");
                });

            modelBuilder.Entity("HOT3.Models.Purchase", b =>
                {
                    b.HasOne("HOT3.Models.Product", "Product")
                        .WithMany()
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Product");
                });
#pragma warning restore 612, 618
        }
    }
}
