// <auto-generated />
using HOT3.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HOT3.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20251012200915_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HOT3.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<string>("ProductBrand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductColor")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ProductStock")
                        .HasColumnType("int");

                    b.HasKey("ProductId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Gooseberry",
                            ProductImageUrl = "DS-DM-Gooseberry.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 14.99m,
                            ProductStock = 32
                        },
                        new
                        {
                            ProductId = 2,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Blossom",
                            ProductImageUrl = "DS-DM-Blossom.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 14.99m,
                            ProductStock = 48
                        },
                        new
                        {
                            ProductId = 3,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Pomegranate & Gold",
                            ProductImageUrl = "DS-DM-PomegranateGold.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 16.99m,
                            ProductStock = 25
                        },
                        new
                        {
                            ProductId = 4,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Cobalt & Silver",
                            ProductImageUrl = "DS-DM-CobaltSilver.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 16.99m,
                            ProductStock = 40
                        },
                        new
                        {
                            ProductId = 5,
                            ProductBrand = "Dragon Shield",
                            ProductColor = "Clear",
                            ProductImageUrl = "DS-PF-Clear.jpg",
                            ProductName = "Matte Dual Sleeves",
                            ProductPrice = 7.99m,
                            ProductStock = 20
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
