// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UncleLeosApp.Models;

#nullable disable

namespace UncleLeosApp.Migrations
{
    [DbContext(typeof(UncleLeosContext))]
    [Migration("20251013200140_AddedMoreProducts1")]
    partial class AddedMoreProducts1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UncleLeosApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Pizza"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Salad"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Appetizer"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dessert"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Beverage"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Merchandise"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Sandwich"
                        },
                        new
                        {
                            CategoryId = 8,
                            CategoryName = "Pasta"
                        });
                });

            modelBuilder.Entity("UncleLeosApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base w/ Sausage, Pepperoni, Onion, Fresh Mushrooms, Black Olives, Green Pepper, topped with Provel Cheese",
                            ProductImage = "Uncle-Leos-deluxe-pizza.png",
                            ProductName = "Uncle Leo's Deluxe",
                            ProductPrice = 19.99m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base Topped w/ Italian Sausage, Pepperoni, Crispy Bacon, and Provel Cheese",
                            ProductImage = "Meat-trio.jpg",
                            ProductName = "Meat Trio",
                            ProductPrice = 18.99m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base Topped w/ Beef, Onion, Tomato, Jalapenos Peppers, and Provel Cheese",
                            ProductImage = "Joeys-Fav.jpeg",
                            ProductName = "Joey's Fave",
                            ProductPrice = 18.99m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            ProductDescription = "Homemade White Sauce Base Topped w/ Grilled Chicken, Yellow Onion, Fresh Mushrooms, Crispy Bacon, Baby Spinach, and Provel Cheese",
                            ProductImage = "Chicken-Delight.jpg",
                            ProductName = "Chicken D'Light",
                            ProductPrice = 20.99m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            ProductDescription = "Homemade White Sauce Base Topped w/ Italian Sausage, Yellow Onion, Crispy Bacon, Baby Spinach, and Provel Cheese",
                            ProductImage = "Sausage-special.jpg",
                            ProductName = "Sausage Special",
                            ProductPrice = 19.99m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            ProductDescription = "FUNGO SAUCE! Special Made Buffalo Sauce Base Topped w/ Grilled Chicken, Yellow Onion, Crispy Bacon, and Provel Cheese",
                            ProductImage = "Fungo-Chicken.png",
                            ProductName = "Fungo Chicken",
                            ProductPrice = 19.99m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            ProductDescription = "Olive Oil Base Topped w/ Tomatoes, Basil, Garlic, and Mozzerella Cheese",
                            ProductImage = "Margherita.jpg",
                            ProductName = "Mariann's Margherita",
                            ProductPrice = 16.99m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base Topped w/ Green Pepper, Yellow Onion, Black Olives, Fresh Mushrooms, and Provel Cheese",
                            ProductImage = "Veggie-Pizza.png",
                            ProductName = "Veggie D'Light",
                            ProductPrice = 16.99m
                        },
                        new
                        {
                            ProductId = 9,
                            CategoryId = 7,
                            ProductDescription = "7\" Sandwich w/ Garlic Butter on the Top Bun, Your Choice of Cheese, Ham, Salami, Pepperoni, Lettuce, Tomato, and Vinaigrette. Served Cold or Hot. Served w/ Side of Choice.",
                            ProductImage = "Italian-Sub.jpg",
                            ProductName = "7\" Italian Sub",
                            ProductPrice = 9.99m
                        },
                        new
                        {
                            ProductId = 10,
                            CategoryId = 7,
                            ProductDescription = "7\" Sandwich w/ Garlic Butter on the Top Bun, Your Choice of Cheese, and Three(3) Saucy Meatballs. Served w/ Side of Choice.",
                            ProductImage = "Meatball-Sub.jpg",
                            ProductName = "7\" Meatball Sub",
                            ProductPrice = 10.99m
                        },
                        new
                        {
                            ProductId = 11,
                            CategoryId = 8,
                            ProductDescription = "Penne Pasta w/ Homemade White Sauce and Broccoli",
                            ProductImage = "Con-Bro.jpg",
                            ProductName = "Pasta Con Broccoli",
                            ProductPrice = 11.99m
                        },
                        new
                        {
                            ProductId = 12,
                            CategoryId = 8,
                            ProductDescription = "Penne Pasta w/ Homemade White Sauce, Fresh Mushrooms, and Crispy Bacon",
                            ProductImage = "Carbonara.jpg",
                            ProductName = "Pasta Carbonara",
                            ProductPrice = 12.99m
                        },
                        new
                        {
                            ProductId = 13,
                            CategoryId = 2,
                            ProductDescription = "Iceburg & Romaine Mix w/ Provel, Cherry Tomatoes, Croutons, and Spinkled on Parmesan",
                            ProductImage = "House-salad.jpg",
                            ProductName = "House Salad",
                            ProductPrice = 7.99m
                        },
                        new
                        {
                            ProductId = 14,
                            CategoryId = 2,
                            ProductDescription = "Iceburg & Romaine Mix w/ Ham, Salami, Provel, Cherry Tomatoes, Croutons, and spinkled on Parmesan",
                            ProductImage = "Chef-Salad.jpg",
                            ProductName = "Deluxe Chef Salad",
                            ProductPrice = 10.99m
                        },
                        new
                        {
                            ProductId = 15,
                            CategoryId = 3,
                            ProductDescription = "Seven(7) Wonton Wrappers Filled w/ Spinache Artichoke Dip. Served w/ Pepper Jelly. Call for orders of 50 or 100.",
                            ProductImage = "Spinocci.jpg",
                            ProductName = "Spinocci",
                            ProductPrice = 10.99m
                        },
                        new
                        {
                            ProductId = 16,
                            CategoryId = 3,
                            ProductDescription = "Nine(9) Wings Deep Fried 'til Crispy and Tossed In Our Special Buffalo Sauce...FUNGO SAUCE! Wings are not breaded. Call for orders of 50 or 100 wings.",
                            ProductImage = "Wings.jpg",
                            ProductName = "Failoni Wings",
                            ProductPrice = 13.99m
                        },
                        new
                        {
                            ProductId = 17,
                            CategoryId = 3,
                            ProductDescription = "10 Breaded Ravioli Deep Fried until Crispy and Golden! Served with Our Homemade Meat Sauce. Call for orders of 50 or 100.",
                            ProductImage = "T-Rav.jpg",
                            ProductName = "Toasted Ravioli",
                            ProductPrice = 8.99m
                        },
                        new
                        {
                            ProductId = 18,
                            CategoryId = 5,
                            ProductDescription = "The familiar, crisp taste of a classic Pepsi, served chilled in a can.",
                            ProductImage = "Pepsi-Can.jpg",
                            ProductName = "Can Pepsi",
                            ProductPrice = 2m
                        },
                        new
                        {
                            ProductId = 19,
                            CategoryId = 4,
                            ProductDescription = "Our Homemade Crust Folded and Filled w/ Apple Filling then Fried until Golden and Sprinkled in Cinnamon Sugar. Served with Icing.",
                            ProductImage = "Apple-Fritter.jpg",
                            ProductName = "Apple Fritter",
                            ProductPrice = 7.99m
                        },
                        new
                        {
                            ProductId = 20,
                            CategoryId = 5,
                            ProductDescription = "The same light, crisp, and refreshing taste of Pepsi, with zero sugar and zero calories.",
                            ProductImage = "diet-pepsi-can",
                            ProductName = "Can Diet Pepsi",
                            ProductPrice = 0.00m
                        });
                });

            modelBuilder.Entity("UncleLeosApp.Models.Product", b =>
                {
                    b.HasOne("UncleLeosApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
