// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UncleLeosApp.Models;

#nullable disable

namespace UncleLeosApp.Migrations
{
    [DbContext(typeof(UncleLeosContext))]
    [Migration("20251013175453_AddSandwich1")]
    partial class AddSandwich1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UncleLeosApp.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            CategoryName = "Pizza"
                        },
                        new
                        {
                            CategoryId = 2,
                            CategoryName = "Salad"
                        },
                        new
                        {
                            CategoryId = 3,
                            CategoryName = "Appetizer"
                        },
                        new
                        {
                            CategoryId = 4,
                            CategoryName = "Dessert"
                        },
                        new
                        {
                            CategoryId = 5,
                            CategoryName = "Beverage"
                        },
                        new
                        {
                            CategoryId = 6,
                            CategoryName = "Merchandise"
                        },
                        new
                        {
                            CategoryId = 7,
                            CategoryName = "Sandwich"
                        });
                });

            modelBuilder.Entity("UncleLeosApp.Models.Product", b =>
                {
                    b.Property<int>("ProductId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductImage")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ProductPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ProductId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductId = 1,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base w/ Sausage, Pepperoni, Onion, Fresh Mushrooms, Black Olives, Green Pepper, topped with Provel Cheese",
                            ProductImage = "Uncle-Leos-deluxe-pizza.png",
                            ProductName = "Uncle Leo's Deluxe",
                            ProductPrice = 19.99m
                        },
                        new
                        {
                            ProductId = 2,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base Topped w/ Italian Sausage, Pepperoni, Crispy Bacon, and Provel Cheese",
                            ProductImage = "Meat-trio.jpg",
                            ProductName = "Meat Trio",
                            ProductPrice = 18.99m
                        },
                        new
                        {
                            ProductId = 3,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base Topped w/ Beef, Onion, Tomato, Jalapenos Peppers, and Provel Cheese",
                            ProductImage = "Joeys-Fav.jpeg",
                            ProductName = "Joey's Fave",
                            ProductPrice = 18.99m
                        },
                        new
                        {
                            ProductId = 4,
                            CategoryId = 1,
                            ProductDescription = "Homemade White Sauce Base Topped w/ Grilled Chicken, Yellow Onion, Fresh Mushrooms, Crispy Bacon, Baby Spinach, and Provel Cheese",
                            ProductImage = "Chicken-Delight.jpg",
                            ProductName = "Chicken D'Light",
                            ProductPrice = 20.99m
                        },
                        new
                        {
                            ProductId = 5,
                            CategoryId = 1,
                            ProductDescription = "Homemade White Sauce Base Topped w/ Italian Sausage, Yellow Onion, Crispy Bacon, Baby Spinach, and Provel Cheese",
                            ProductImage = "Sausage-special.jpg",
                            ProductName = "Sausage Special",
                            ProductPrice = 19.99m
                        },
                        new
                        {
                            ProductId = 6,
                            CategoryId = 1,
                            ProductDescription = "FUNGO SAUCE! Special Made Buffalo Sauce Base Topped w/ Grilled Chicken, Yellow Onion, Crispy Bacon, and Provel Cheese",
                            ProductImage = "Fungo-Chicken.png",
                            ProductName = "Fungo Chicken",
                            ProductPrice = 19.99m
                        },
                        new
                        {
                            ProductId = 7,
                            CategoryId = 1,
                            ProductDescription = "Olive Oil Base Topped w/ Tomatoes, Basil, Garlic, and Mozzerella Cheese",
                            ProductImage = "Margherita.jpg",
                            ProductName = "Mariann's Margherita",
                            ProductPrice = 16.99m
                        },
                        new
                        {
                            ProductId = 8,
                            CategoryId = 1,
                            ProductDescription = "Homemade Red Sauce Base Topped w/ Green Pepper, Yellow Onion, Black Olives, Fresh Mushrooms, and Provel Cheese",
                            ProductImage = "Veggie-Pizza.png",
                            ProductName = "Veggie D'Light",
                            ProductPrice = 16.99m
                        });
                });

            modelBuilder.Entity("UncleLeosApp.Models.Product", b =>
                {
                    b.HasOne("UncleLeosApp.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });
#pragma warning restore 612, 618
        }
    }
}
