// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using UncleLeosPizza.Models;

#nullable disable

namespace UncleLeosPizza.Migrations
{
    [DbContext(typeof(UncleLeosContext))]
    partial class UncleLeosContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("UncleLeosPizza.Models.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Pizza"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Salad"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Appetizer"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Dessert"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Beverage"
                        },
                        new
                        {
                            CategoryId = 6,
                            Name = "Merchandise"
                        });
                });

            modelBuilder.Entity("UncleLeosPizza.Models.Item", b =>
                {
                    b.Property<int>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ItemId"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ItemId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Items");

                    b.HasData(
                        new
                        {
                            ItemId = 1,
                            CategoryId = 1,
                            Description = "Classic cheese pizza with tomato sauce and mozzarella cheese",
                            Name = "Cheese Pizza"
                        },
                        new
                        {
                            ItemId = 2,
                            CategoryId = 1,
                            Description = "Pepperoni pizza with tomato sauce and mozzarella cheese",
                            Name = "Pepperoni Pizza"
                        },
                        new
                        {
                            ItemId = 3,
                            CategoryId = 1,
                            Description = "Vegetarian pizza with tomato sauce, mozzarella cheese, bell peppers, onions, and mushrooms",
                            Name = "Veggie Pizza"
                        },
                        new
                        {
                            ItemId = 4,
                            CategoryId = 2,
                            Description = "Crisp romaine lettuce, croutons, and Caesar dressing",
                            Name = "Caesar Salad"
                        },
                        new
                        {
                            ItemId = 5,
                            CategoryId = 2,
                            Description = "Mixed greens, feta cheese, olives, cucumbers, and tomatoes with Greek dressing",
                            Name = "Greek Salad"
                        },
                        new
                        {
                            ItemId = 6,
                            CategoryId = 3,
                            Description = "Spicy buffalo wings served with blue cheese dressing",
                            Name = "Chicken Wings"
                        });
                });

            modelBuilder.Entity("UncleLeosPizza.Models.ItemSize", b =>
                {
                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("SizeId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ItemId", "SizeId");

                    b.HasIndex("SizeId");

                    b.ToTable("ItemSizes");

                    b.HasData(
                        new
                        {
                            ItemId = 5,
                            SizeId = 1,
                            Price = 6.99m
                        },
                        new
                        {
                            ItemId = 6,
                            SizeId = 1,
                            Price = 7.99m
                        },
                        new
                        {
                            ItemId = 6,
                            SizeId = 2,
                            Price = 12.99m
                        });
                });

            modelBuilder.Entity("UncleLeosPizza.Models.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("OrderId");

                    b.HasIndex("UserId");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderItemId"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<string>("OrderId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrderId1")
                        .HasColumnType("int");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("OrderItemId");

                    b.HasIndex("ItemId");

                    b.HasIndex("OrderId1");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.Size", b =>
                {
                    b.Property<int>("SizeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SizeId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SizeId");

                    b.ToTable("Sizes");

                    b.HasData(
                        new
                        {
                            SizeId = 1,
                            Name = "Small"
                        },
                        new
                        {
                            SizeId = 2,
                            Name = "Medium"
                        },
                        new
                        {
                            SizeId = 3,
                            Name = "Large"
                        });
                });

            modelBuilder.Entity("UncleLeosPizza.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.Item", b =>
                {
                    b.HasOne("UncleLeosPizza.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.ItemSize", b =>
                {
                    b.HasOne("UncleLeosPizza.Models.Item", "Item")
                        .WithMany("ItemSizes")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UncleLeosPizza.Models.Size", "Size")
                        .WithMany("ItemSizes")
                        .HasForeignKey("SizeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Size");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.Order", b =>
                {
                    b.HasOne("UncleLeosPizza.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.OrderItem", b =>
                {
                    b.HasOne("UncleLeosPizza.Models.Item", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("UncleLeosPizza.Models.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId1")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.Item", b =>
                {
                    b.Navigation("ItemSizes");
                });

            modelBuilder.Entity("UncleLeosPizza.Models.Size", b =>
                {
                    b.Navigation("ItemSizes");
                });
#pragma warning restore 612, 618
        }
    }
}
